### ISSUE TITLE
Missing support for asm_inline in Linux 5.4

### ISSUE THREAD

**Issue by tamilnewzealand** [jackthompsonnz/socketcan-linux-5.0#1]
The following issue is present when compiling under Linux 5.4+.

```
./arch/x86/include/asm/segment.h:254:2: error: expected '(' after 'asm'
        alternative_io ("lsl %[seg],%[p]",
        ^
./arch/x86/include/asm/alternative.h:240:2: note: expanded from macro 'alternative_io'
        asm_inline volatile (ALTERNATIVE(oldinstr, newinstr, feature)   \
        ^
include/linux/compiler_types.h:210:24: note: expanded from macro 'asm_inline'
#define asm_inline asm __inline
```

This issue is directly caused by the following commit where asm_inline has been switched with asm:
[torvalds/linux@40576e5](https://github.com/torvalds/linux/commit/40576e5e63ea5eeab814de7af83ad09dd64134ee)

Using GCC 6.5

**Comment by jackthompsonnz** [comment]
On kernel 5.4.0-42 compiling with GCC 9.3.0 i see no issues? Maybe try updating your GCC version and report back

**Comment by tamilnewzealand** [comment]
Working with gcc-7 and newer.
