### ISSUE TITLE
Update the time data types used to 5.6+ kernels.

### ISSUE THREAD

**Issue by mortlind** [jackthompsonnz/socketcan-linux-5.0#2]
Hi @jackthompsonnz ,

We discovered that kernels newer than ~5.6 have a different time data structure and do no longer support the `timeval` struct. Do you have a quick, or slow, fix for this?

Thanks for a great library, by the way :-)

**Comment by adivardi** [comment]
Any updates/ideas on that? I'm planning to upgrade for bionic to focal and wonder if this will be an issue

**Comment by jackthompsonnz** [comment]
Hey guys, pretty snowed under with lots of projects at work at the moment, don't really have much time to look into it. I'm running focal kernel 5.4 and it's working fine for me right now, if / when i run into issues it'll become more of a pressing issue for me to fix haha. Feel free to put up a PR and I'll have a look if you have any ideas

**Comment by Mixaill** [comment]
@mortlind @adivardi 

You can check fixes in the PR, tested on 5.8

**Comment by mortlind** [comment]
@Mixaill Thanks for the effort. But a friend of mine fixed this in a fork on GitLab only yesterday: https://gitlab.com/trondprotech/ixxat-socketcan. We will be proceeding with that project, since it also nicely builds a deb-package for us.

**Comment by Mixaill** [comment]
:D, DKMS is the really nice upgrade. 
I've also planned to make .deb but thank you for your effort!
