### ISSUE TITLE
Using low speed on Ixxat USB-to-CAN v2

### ISSUE THREAD

**Issue by oddek** [jackthompsonnz/socketcan-linux-5.0#3]
Hello. 

Has anybody been able to get this driver to work using low-speed/fault-tolerant?

It seems like the default for port CAN1/LS is high-speed, and there does not seem to be any settings to specify low speed in socketcan?

**Comment by Mixaill** [comment]
I think it should `just work` if you setup the low baudrate via `ip link set canX type can bitrate YYYYY`

**Comment by jackthompsonnz** [comment]
As above, you can change the bitrate via iplink and it _should_ just work

**Comment by oddek** [comment]
Im sorry, I should have perhaps formulated my question better. 

In the datasheet for the V2 automotive, it says that controlling if the high-speed or fault-tolerant/low-speed transceiver is use is done in software. 50000 for instance, is a valid bit-rate for both of these, as the main difference between high-speed and low-speed/fault-tolerant lies in how the bus is terminated. 

On Windows, you can choose which of these transceivers you want to use, but as I cannot find any settings for this in Linux using ip-link, it defaults to the high-speed transceiver.

**Comment by Mixaill** [comment]
So, the automotive version has built-in terminator in LS mode.

I think you should try ECI driver
https://www.ixxat.com/technical-support/resources/downloads-and-documentation?ordercode=1.01.0281.12001

It has its own API, but looks like it has possibility to select coupling
![image](https://user-images.githubusercontent.com/704382/115209243-18083980-a106-11eb-8ea6-22dcb996045f.png)

**Comment by oddek** [comment]
> So, the automotive version has built-in terminator in LS mode.
> 
> I think you should try ECI driver
> https://www.ixxat.com/technical-support/resources/downloads-and-documentation?ordercode=1.01.0281.12001
> 
> It has its own API, but looks like it has possibility to select coupling
> ![image](https://user-images.githubusercontent.com/704382/115209243-18083980-a106-11eb-8ea6-22dcb996045f.png)

Thanks a lot. I'll give that a go!

**Comment by oddek** [comment]
The ECI driver did not really fit my needs, but if anyone else encounters this problem i recommend looking at the solution provided by HMS support:
https://forum.hms-networks.com/t/using-low-speed-with-socketcan-driver-on-usb-to-can-v2/68572/6

They provide instructions on how to modify the driver, to set static LS mode.
