### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by GoNisic** [jackthompsonnz/socketcan-linux-5.0#6]
System:
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS (running on a virtual machine)
Release:	        20.04
Codename:	focal

Hardware:
Product: USB-to-CAN V2
Manufacturer: IXXAT

After compiling and installation, I get following feedback using dmesg
[  311.531537] ixx_usb 1-1:1.0 can0: attached to USB-to-CAN_V2 channel 0 (device HW425745)

"sudo ip link set up can0" is followed by the error message
Segmentation fault (core dumped)

**Comment by jackthompsonnz** [comment]
Are you still getting this issue? Maybe try updating to the latest version, it now supports kernel 5.11 - sorry I missed this, re-open if still exists
